config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :organizations
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/organization.rb
class Organization < ApplicationRecord
    belongs_to :user
end

app/models/plan.rb
class Plan
    PLANS = [:free, :premium]

    def self.options
        PLANS.map{ |plan| [plan.capitalize, plan] }
    end
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_tenant :organization
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :organization

  before_validation :set_organization

  def set_organization
    self.build_organization
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    #before_action :authenticate_user!
    set_current_tenant_by_subdomain_or_domain(:organization, :subdomain, :domain)
    
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:plan])
    end

    def set_current_organization
        return unless current_user.present?
        current_organization = current_user.organization
        ActsAsTenant.current_tenant = current_organization
    end
end

app/controllers/confirmation_controllers.rb
class ConfirmationControllers < ActsAsTenant::ConfirmationControllers

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_organization, only: %i[ show edit update destroy ]
  set_current_tenant_by_subdomain_or_domain(:organization, :subdomain, :domain)

  before_action :check_subdomain

  def check_subdomain
    unless request.subdomain == current_user.subdomain
      redirect_to root_path, alert: "You are not authorized to access that subdomain."
    end
  end
  
  # GET /organizations or /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1 or /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations or /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to organization_url(@organization), notice: "Organization was successfully created." }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1 or /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organization_url(@organization), notice: "Organization was successfully updated." }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1 or /organizations/1.json
  def destroy
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url, notice: "Organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:name, :subdomain, :domain)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert fade in alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), type: "button",
         class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<% if current_user %>
    <h3>Organization: <%= current_user.organization.name %></h3>

<% else %>

    <div class="jumbotron">
    <h2>Welcome to Roberts</h2>

    <p class="lead">
        You'll love managing your project with our SaaS application. Please take a look at our great plans
    </p>
    </div>

    <div class="row">
        <div class="plans clearfix">
        <div class="col-lg-3 col-lg-offset-3 plan">
        <h2>Free Plan</h2>

        <div class="price pull-right">
            Price: Free
        </div>

        <div class="features">
            <ul>
                <li>Unlimited file uploads</li>
                <li>Responsive design</li>
                <li>Access anywhere</li>
                <li>1 project</li>
            </ul>
        </div>

        <p>
            <%= link_to 'Sign Up', new_user_registration_path(plan: 'free'), class: 'btn btn-primary sign-up' %>
        </p>
        </div>

        <div class="col-lg-3 plan">
        <h2>Premium Plan</h2>

        <div class="price pull-right">
            Price: $10
        </div>

        <div class="features">
            <ul>
                <li>Unlimited file uploads</li>
                <li>Responsive design</li>
                <li>Access anywhere</li>
                <li class='extra'>Unlimited projects</li>
            </ul>
        </div>

        <p>
            <%= link_to 'Sign Up', new_user_registration_path(plan: 'premium'), class: 'btn btn-primary sign-up' %>
        </p>

        </div>

        </div>

    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Roberts" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

  
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Roberts</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-right col-md-4">
            <% if current_user %>

            <li class="col-md-8 user-name">

              <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>

            </li>

            <li class="col-md-1"> </li>

            <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'Logout', :method => :get) %></li>

            <% else %>

            <li class="col-md-4 pull-right">

              <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>

            </li>

            <% end %>

            </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      <footer>
        <p>&copy; Roberts 2023</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/organizations/_form.html.erb
<%= form_with(model: organization) do |form| %>
  <% if organization.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :subdomain, style: "display: block" %>
    <%= form.text_field :subdomain %>
  </div>

  <div>
    <%= form.label :domain, style: "display: block" %>
    <%= form.text_field :domain %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/_organization.html.erb
<div id="<%= dom_id organization %>">
  <p>
    <strong>Name:</strong>
    <%= organization.name %>
  </p>

  <p>
    <strong>Subdomain:</strong>
    <%= organization.subdomain %>
  </p>

  <p>
    <strong>Domain:</strong>
    <%= organization.domain %>
  </p>

</div>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render "form", organization: @organization %>

<br>

<div>
  <%= link_to "Show this organization", @organization %> |
  <%= link_to "Back to organizations", organizations_path %>
</div>

app/views/organizations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Organizations</h1>

<div id="organizations">
  <% @organizations.each do |organization| %>
    <%= render organization %>
    <p>
      <%= link_to "Show this organization", organization %>
    </p>
  <% end %>
</div>

<%= link_to "New organization", new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render "form", organization: @organization %>

<br>

<div>
  <%= link_to "Back to organizations", organizations_path %>
</div>

app/views/organizations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @organization %>

<div>
  <%= link_to "Edit this organization", edit_organization_path(@organization) %> |
  <%= link_to "Back to organizations", organizations_path %>

  <%= button_to "Destroy this organization", @organization, method: :delete %>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Organization:</strong>
    <%= project.organization_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>